AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Parameters:
    Handlername:
        Type: String

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: !Sub "${Handlername}"
      Runtime: nodejs12.x
      CodeUri: src/
